#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use josegonzalez\Dotenv\Loader;
use Spoof\Commands\MergeLatestTagCommand;
use Spoof\Commands\PrMergeCommand;
use Spoof\Commands\PublishReleaseCommand;
use Symfony\Component\Console\Application;

$envLoader = (new Loader(__DIR__.'/.env'))
    ->parse()
    ->expect('DESTINATION_URL', 'GITHUB_SECRET', 'GITHUB_TOKEN')
    ->toEnv(true);

$application = new Application('spoof', '1.0.1');

$application->add(new PrMergeCommand());
$application->add(new PublishReleaseCommand());
$application->add(new MergeLatestTagCommand());

$application->run();
