#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use josegonzalez\Dotenv\Loader;
use Spoof\Commands\PrMergeCommand;
use Symfony\Component\Console\Application;

$envLoader = (new Loader('.env'))
    ->parse()
    ->expect('DESTINATION_URL', 'GITHUB_SECRET')
    ->toEnv(true);

(new Application('spoof', '0.0.1'))
    ->add(new PrMergeCommand())
    ->getApplication()
    ->setDefaultCommand('PrMerge', true)
    ->run();
